---

- name: Configure Kibana v4.0 - v4.1
  become: yes
  template:
    src: kibana.v4.0_4.1.yml.j2
    dest: "{{ sansible_kibana_install_dir }}/config/kibana.yml"
  notify:
    - restart kibana
  when: sansible_kibana_version is version_compare('4.2', '<')

- name: Configure Kibana v4.2+
  become: yes
  template:
    src: kibana.v4.2_4.5.yml.j2
    dest: "{{ sansible_kibana_install_dir }}/config/kibana.yml"
  notify:
    - restart kibana
  when: sansible_kibana_version is version_compare('4.2', '>=')

- name: Ensure Kibana Service is Started
  become: yes
  service:
    name: kibana
    state: started
